### ISSUE TITLE
 sticker not scaling

### ISSUE THREAD

**Issue by iamjitendrasinh** [iamutkarshtiwari/Ananas#18]
sticker not scaling

**Comment by iamjitendrasinh** [comment]
Fixed by moving "text_sticker_panel_frame" to top in "work_space" FrameLayout in activity_image_edit.xml

anyway, Thanks for your work!!

**Comment by iamutkarshtiwari** [comment]
@iamjitendrasinh Thank you for reporting this issue. I'd appreciate if you can make a PR for this fix :)

**Comment by iamutkarshtiwari** [comment]
Done https://github.com/iamutkarshtiwari/Ananas/commit/c0dfa2c92fbfbe11a96b32b434639fc8d421d51e
