### ISSUE TITLE
where is launcher activity?

### ISSUE THREAD

**Issue by CrazyCoderAndroid** [iamutkarshtiwari/Ananas#3]
which activity is used as a launcher activity?

**Comment by iamutkarshtiwari** [comment]
https://github.com/iamutkarshtiwari/Ananas#starting-the-photoeditor-activity 
It's `EditImageActivity`

**Comment by iamutkarshtiwari** [comment]
@CrazyCoderAndroid I have added the [sample here](https://github.com/iamutkarshtiwari/Ananas/tree/master/demo)
