### ISSUE TITLE
Configurable features are not considering settings from ImageEditorIntentBuilder

### ISSUE THREAD

**Issue by takacsm12** [iamutkarshtiwari/Ananas#39]

**Comment by SalvadorAngel** [comment]
i have same issue

this configuration:
val intent = ImageEditorIntentBuilder(this, temp.absolutePath, tempEdit!!.absolutePath)
                        .withAddText() // Add the features you need
                        .withPaintFeature()
                        .withRotateFeature()
                        .withCropFeature()
                        .withBrightnessFeature()
                        .withSaturationFeature()
                        .forcePortrait(false)  // Add this to force portrait mode (It's set to false by default)
                        .build()
add all features not only the selecteds

**Comment by iamutkarshtiwari** [comment]
@takacsm12 @SalvadorAngel 
I am unable to reproduce it. 
Could you please post the device and platform on which this issue happens?

**Comment by SalvadorAngel** [comment]
> @takacsm12 @SalvadorAngel
> I am unable to reproduce it.
> Could you please post the device and platform on which this issue happens?

 compileSdkVersion 28
    defaultConfig {
        applicationId "XXX"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 13023
        versionName "3.3.0"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
-androidx.appcompat:appcompat:1.1.0

device was sony xperia XA2:H3123 running android 9

**Comment by lorobode** [comment]
Same here. I tried to put just `withAddText()` and all the features still appears

**Comment by iamutkarshtiwari** [comment]
Thank you, everyone! My bad. A commit got lost in the master that caused this bug. Let me fix it.

**Comment by iamutkarshtiwari** [comment]
@takacsm12 Thank you for your contribution! I have fixed the MainMenuFragment instead.
