### ISSUE TITLE
Unable to start activity 

### ISSUE THREAD

**Issue by GiaSra92** [iamutkarshtiwari/Ananas#43]
Unable to start activity ComponentInfo{com.test.app/iamutkarshtiwari.github.io.ananas.editimage.EditImageActivity}: android.view.InflateException: Binary XML file line #94: Binary XML file line #94: Error inflating class iamutkarshtiwari.github.io.ananas.editimage.layout.ZoomLayout

if it is not enabled
JavaVersion.VERSION_1_8
the following error occurs

the following options must be enabled in the build.grandle (Module App) by entering the following code

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

I also remember to add in the Manifest

  <activity
            android: name = "iamutkarshtiwari.github.io.ananas.picchooser.SelectPictureActivity">
        </ Activity>

        
        <activity
            android: name = "iamutkarshtiwari.github.io.ananas.editimage.EditImageActivity"
            Android: windowSoftInputMode = "adjustPan">
        </ Activity>

to avoid exceptions during the execution phase.

**Comment by iamutkarshtiwari** [comment]
@GiaSra92 Does it mean `JavaVersion.VERSION_1_8` needs to be added to the Gradle of the project in which the library is implemented?

**Comment by iamutkarshtiwari** [comment]
I think this is what you meant: https://github.com/iamutkarshtiwari/Ananas/pull/45

**Comment by iamutkarshtiwari** [comment]
Please feel free to reopen if anyone faces the issue again.
