### ISSUE TITLE
SelectPictureActivity opens empty grid with names

### ISSUE THREAD

**Issue by hgopi** [iamutkarshtiwari/Ananas#52]
First of all, thanks for this beautiful library. 

I was having Manifest merge issue while adding this library with my application. Later I resolved that issue by updating the manifest file with two attributes:

tools:node="merge"
tools:replace="android:label,android:allowBackup,android:supportsRtl"

After I am having one issue when starting the SelectPictureActivity from my application. It shows empty black grids with gallery names but no images. While clicking the empty grids it returns null. 

Here is my application gradle and other info:

Kotlin version: 1.3.50
Ananas Library version: 1.2.3
Included the  JavaVersion.VERSION_1_8 in compilerOptions.
Not using RxJava.  
minSdkVersion: 21

Thanks in advance.

**Comment by hgopi** [comment]
I have resolved this issue by doing:

- added android:requestLegacyExternalStorage="true" in application tag in manifest. This enables external storage in Android Q and later.

- Requested WRITE_EXTERNAL_STORAGE to load the images using Glide. Without this Glide throws permission error.

Thanks.

**Comment by iamutkarshtiwari** [comment]
Thank you for sharing the solution!
