### ISSUE TITLE
can you explain what are sourceImagePath, outputFilePath

### ISSUE THREAD

**Issue by chigup** [iamutkarshtiwari/Ananas#54]

**Comment by s-hussain639** [comment]
Hello have you got it Please can you explain it here thanks

**Comment by joemerritt** [comment]
Hi Hussain did you get a response for this?

**Comment by s-hussain639** [comment]
Yes I got it please by myself. The source path is the image path which you
want to edit mean form sd card  like sdcard/images/myimage
and the out file path is the path where you want to store it. you can
create a temp file and store it there after that you can clear that thing.
Feel free to contact.
Sorry for late replay i was out of station.
Saddam
