### ISSUE TITLE
cannot resolve 'OUTPUT_PATH' in onActivityResult

### ISSUE THREAD

**Issue by mobin1623** [iamutkarshtiwari/Ananas#57]
It seems that the there is no variable defined to get the new image output file path.

String newFilePath = data.getStringExtra(EditImageActivity.OUTPUT_PATH);

**OUTPUT_PATH** :- not defined
Please assist.

**Comment by thirstycoda** [comment]
Try using ImageEditorIntentBuilder.OUTPUT_PATH

**Comment by iamutkarshtiwari** [comment]
Should be solved in the new version `1.2.5`. Please feel free to re-open if you still face the issue.
