### ISSUE TITLE
Add option for disable Default ActionBar

### ISSUE THREAD

**Issue by james04gr** [iamutkarshtiwari/Ananas#58]
@iamutkarshtiwari 
In my application the default theme has the default ActionBar of the android application that the Android studio provides.
So when i open the EditImageActivity its like i see two action bars. I want to keep your actionBar and hide mine. How can i do that?

![109894721_3358278964236846_7973803831109147401_n](https://user-images.githubusercontent.com/24235421/88057301-8e254300-cb6a-11ea-8563-ce50ba654fd8.jpg)

**Comment by james04gr** [comment]
@iamutkarshtiwari  I would suggest to show or hide it according to a parameter in the Intent builder. 
Piece of cake i believe! :)

**Comment by iamutkarshtiwari** [comment]
Thanks for your suggestion! Let me add this enhancement.

**Comment by james04gr** [comment]
Excellent. Let us know when you r done!! :)

**Comment by james04gr** [comment]
> Thanks for your suggestion! Let me add this enhancement.

Hello. I am just asking if the above request is going to get fixed soon. Thnx!

**Comment by iamutkarshtiwari** [comment]
I am on it 👍

**Comment by iamutkarshtiwari** [comment]
@james04gr Please try the new version :)

**Comment by james04gr** [comment]
Everything is ok. Thank you for your respond!!
