### ISSUE TITLE
Brush is not smooth

### ISSUE THREAD

**Issue by Hmoadeb** [iamutkarshtiwari/Ananas#60]
I can't make a smooth drawing using Brush 
![2020-08-10](https://user-images.githubusercontent.com/67900637/89775456-be278c80-daff-11ea-9c2e-3eb43ea33e00.jpg)

**Comment by iamutkarshtiwari** [comment]
@Hmoadeb Thanks for reporting this issue. Unfortunately, I am unable to reproduce the issue you mentioned. I'd appreaciate if you could share the steps to reproduce it. Please feel free to reopen this issue.

<img src="https://user-images.githubusercontent.com/6258810/106357109-6dbf1800-6347-11eb-8240-adb87b5eae8a.png"  width="300" height="600">
