### ISSUE TITLE
Failed to resolve: com.github.iamutkarshtiwari:Ananas:1.2.4

### ISSUE THREAD

**Issue by ihassanali259** [iamutkarshtiwari/Ananas#63]
When trying to implement this library android studio shows this error.

**Comment by iamutkarshtiwari** [comment]
I am able to resolve the library. Could you please try again? I could be because of jitpack server issues.

**Comment by Jackyto** [comment]
Same for me here, just started a new project and added implementation, says "Failed to resolve"

**Comment by ihassanali259** [comment]
A better solution is to use [this](https://github.com/burhanrashid52/PhotoEditor) library as an alteranative
