### ISSUE TITLE
Google Play Console Conflict

### ISSUE THREAD

**Issue by joemerritt** [iamutkarshtiwari/Ananas#73]
Hi Guys,

I've just tried to upload the abb to google play console. Unfortunately it won't allow me to upload. 

I've uninstalled the implementation and the new abb uploaded with no problems. But when I reinstall 
implementation 'com.github.iamutkarshtiwari:Ananas:1.2.4', 
the issue is there again.

Any suggestions on how to look for the conflict/issue?

Cheers

**Comment by farrakhj** [comment]
Hello,

Can you kindly share the error of Google Play console?

Regards,
Farrakh

**Comment by iamutkarshtiwari** [comment]
Hi @joemerritt , as @farrakhj mentioned, it would be helpful if you could share the error you get on Google Play console. That way we can debug and resolve the issue.

**Comment by iamutkarshtiwari** [comment]
@joemerritt Please try the latest version `1.2.6`. If you still face this issue, feel free to re-open this ticket.
