### ISSUE TITLE
Cannot resolve symbol 'OUTPUT_PATH'

### ISSUE THREAD

**Issue by Gaurav-V7** [iamutkarshtiwari/Ananas#80]
![Screenshot (4)](https://user-images.githubusercontent.com/37897930/103093869-b76a6380-4621-11eb-89b5-989a2a8cdb77.png)
I have found this library on internet, everything works fine. No Problem at all. But after all implementation, I have found that you have not added OUTPUT_PATH static variable not added in class which returns the edited image path in activity and You have saying the variable is available in your example. Please check out what's the issue and provide version which have this variable. So I can install that version of library in my project. Thank You.

**Comment by iamutkarshtiwari** [comment]
Hi @Gaurav-V7 , thanks for reporting this! We have updated the example code in the README. Please try the latest version `1.2.5` and let us know if there are any issues.
