### ISSUE TITLE
App compiling issue

### ISSUE THREAD

**Issue by hinnan** [iamutkarshtiwari/Ananas#86]
I have followed all your steps which you determined for importing library but I am still unable to import the Editoractivity into my project. Please help me

**Comment by iamutkarshtiwari** [comment]
Hi @hinnan, could you please share logs for the error you are facing when compiling?

**Comment by khawajaetisam99** [comment]
Change the version from 1.2.5 -> 1.2.3
solved!

**Comment by iamutkarshtiwari** [comment]
This was fixed in this commit https://github.com/iamutkarshtiwari/Ananas/pull/94
Please feel free to re-open this ticket if the issue persists.
