### ISSUE TITLE
Can't Implement

### ISSUE THREAD

**Issue by DevAdeel** [iamutkarshtiwari/Ananas#88]
I am unable to implement library in my project.

Getting following error

Failed to resolve: com.github.iamutkarshtiwari:Ananas:1.2.5

**Comment by DevAdeel** [comment]
Issue solved 
Changes the version from 1.2.5 -> 1.2.3

**Comment by iamutkarshtiwari** [comment]
@DevAdeel Please try the latest version `1.2.6`. It has bug fixes and improved photo picker.
