### ISSUE TITLE
com.rahat.editorapp E/TAG: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter outputPath

### ISSUE THREAD

**Issue by rahat14** [iamutkarshtiwari/Ananas#89]
requesting OUTPUT File Path but  all  ready giving it 
on Andorid 10 

File outputFile = FileUtils.genEditFile();
        Log.d("TAG", "editImageClick: "  + outputFile.getAbsolutePath());
        try {

            Intent intent = new ImageEditorIntentBuilder(this, path, outputFile.getAbsolutePath())
                    .withAddText()
                    .withPaintFeature()
                    .withFilterFeature()
                    .withRotateFeature()
                    .withCropFeature()
                    .withBrightnessFeature()
                    .withSaturationFeature()
                    .withOutputPath(outputFile.getAbsolutePath())
                    .withBeautyFeature()
                    .withStickerFeature()
                    .forcePortrait(true)
                    .build();

            EditImageActivity.start(this, intent, ACTION_REQUEST_EDITIMAGE);
        } catch (Exception e) {
          //  Toast.makeText(this, R.string.iamutkarshtiwari_github_io_ananas_not_selected, Toast.LENGTH_SHORT).show();
            Log.e("TAG", e.getMessage());
        }

**Comment by iamutkarshtiwari** [comment]
This was fixed in this commit https://github.com/iamutkarshtiwari/Ananas/pull/94
Please feel free to re-open this ticket if the issue persists.
