### ISSUE TITLE
Getting crash in Android 11(R) during selecting album

### ISSUE THREAD

**Issue by Gaurav2621998** [iamutkarshtiwari/Ananas#90]
![WhatsApp Image 2021-05-11 at 12 22 09 PM](https://user-images.githubusercontent.com/27393610/117780165-01648680-b25d-11eb-8b0c-b56728e8d304.jpeg)

Device Name - redmi k30
Build Version - 30

**Comment by iamutkarshtiwari** [comment]
This was fixed in this commit https://github.com/iamutkarshtiwari/Ananas/pull/94
Please feel free to re-open this ticket if the issue persists.

**Comment by Gaurav2621998** [comment]
Yes, now working fine. Thanks buddy. @iamutkarshtiwari
