### ISSUE TITLE
getting issue while add lib in kotlin project 

### ISSUE THREAD

**Issue by jeevanvns** [iamutkarshtiwari/Ananas#91]
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.iamutkarshtiwari:Ananas:1.2.5.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by AliAzaz** [comment]
Getting the same issue because @iamutkarshtiwari you didn't create release: See this on jitpack:
![image](https://user-images.githubusercontent.com/12116478/120169791-be714f80-c219-11eb-9816-9598decdff3f.png)

**Comment by iamutkarshtiwari** [comment]
This was fixed in this commit https://github.com/iamutkarshtiwari/Ananas/pull/94
Please feel free to re-open this ticket if the issue persists.
