### ISSUE TITLE
upload image issue

### ISSUE THREAD

**Issue by farwahmehmood** [iamutkarshtiwari/Ananas#92]
for the very first the when we install our apk of app. it does not upload image to image editor and after that it starts uploading. but when we clear data of our app and start our app again it does not upload image in editor for first time.

**Comment by iamutkarshtiwari** [comment]
This was fixed in this commit https://github.com/iamutkarshtiwari/Ananas/pull/94
Please feel free to re-open this ticket if the issue persists.
