### ISSUE TITLE
Image not loading on First run of the app

### ISSUE THREAD

**Issue by AkkiBuoy** [iamutkarshtiwari/Ananas#93]
` Disposable loadImageDisposable = loadImage(filePath)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .doOnSubscribe(subscriber -> loadingDialog.show())
                .doFinally(() -> loadingDialog.dismiss())
                .subscribe(processedBitmap -> changeMainBitmap(processedBitmap, false), e -> showToast(R.string.iamutkarshtiwari_github_io_ananas_load_error));
`

In EditImageActivity the subscribe method is not called on first run of the app. As a result changeMainBitmap() not executing and black screen appears.

**Comment by iamutkarshtiwari** [comment]
This was fixed in this commit https://github.com/iamutkarshtiwari/Ananas/pull/94
